Repository hyukjinKimm/skyscanner-sopt35, pull requests merged in 2024-11, with the labels that each got.

#2 [FEAT] PR 테스트
  src/main/java/sopt35/skyscanner/test.txt
Labels: feat

#4 [feat] 개발 완료!
  src/main/java/sopt35/skyscanner/test.txt
  src/main/resources/application.yml
Labels: feat, fix

#7 [test] 자동배포 테스트
  src/main/java/sopt35/skyscanner/controller/TestController.java
Labels: test

#9 [TEST] 빌드가 깨지면 머지가 안됩니다.
  src/main/java/sopt35/skyscanner/controller/TestController.java
Labels: test

#21 [FEAT] 배포 자동화 구현 완료
  src/main/java/sopt35/skyscanner/controller/TestController.java
Labels: feat

#26 [FEAT] 배포 자동화
  src/main/java/sopt35/skyscanner/controller/TestController.java
Labels: test

#29 [FEAT] 랜딩페이지 항공권 호출 API
  src/main/java/sopt35/skyscanner/controller/CardController.java
  src/main/java/sopt35/skyscanner/dto/CardListResponse.java
  src/main/java/sopt35/skyscanner/dto/CardResponse.java
  src/main/java/sopt35/skyscanner/repository/Card.java
  src/main/java/sopt35/skyscanner/repository/CardRepository.java
  src/main/java/sopt35/skyscanner/service/CardService.java
Labels: feat

#31 [FEAT] 위시리스트 API 구현
  src/main/java/sopt35/skyscanner/controller/FlightController.java
  src/main/java/sopt35/skyscanner/dto/WishListResponse.java
  src/main/java/sopt35/skyscanner/dto/WishResponse.java
  src/main/java/sopt35/skyscanner/repository/Flight.java
  src/main/java/sopt35/skyscanner/repository/FlightRepository.java
  src/main/java/sopt35/skyscanner/service/FlightService.java
Labels: feat
